### PR TITLE
Modernize and fix docs a bit

### PR DESCRIPTION
**Pull request by svenstaro**
I really like this neat little crate but I think it could use some love. There were some typos and some parts don't follow Rust best-practices. For instance, you're not supposed to directly `impl ToString` but instead `impl Display`. I also fixed the formatting a bit.

### CODE REVIEW

**Comment by svenstaro** [comment]
@FreeMasen ping

**Review by FreeMasen — APPROVED** [review]
Looks good. Sorry it took so long I didn't get the initial notification for some reason

**Comment by svenstaro** [comment]
Alright, mind making a release with this?

**Comment by FreeMasen** [comment]
This was released as 0.2.0

**Pull request merged**
